import { hashPassword } from './auth.js';
import { nowIso } from './utils.js';

const passwordHash = hashPassword('campusguard', 'campusguard-seed-salt');

export const seedKnowledge = [
  {
    id: 'KB-1',
    title: 'MITCORER admission documents',
    category: 'Documents',
    source: 'Verified admission checklist',
    text: 'Admission reporting commonly requires CET or JEE scorecard, 10th marksheet, 12th marksheet or diploma marksheets for DSE, transfer certificate, domicile or nationality proof, CAP allotment letter, caste certificate if applicable, caste validity if applicable, non-creamy layer if applicable, income certificate for concession claims, passport size photographs, Aadhaar, and bank details where scholarship processing is needed.',
    status: 'Published',
  },
  {
    id: 'KB-2',
    title: 'MITCORER fees AY 2026-27',
    category: 'Fees',
    source: 'Approved fee records shared for AY 2026-27',
    tags: ['fees', 'fee structure', 'academic fee', 'open fee', 'sc fee', 'st fee', 'dse fee', 'first year fee'],
    text: 'First Year Engineering fees for AY 2026-27 include Open or OMS total INR 1,05,000, Open EBC EWS OBC SEBC boys INR 61,109, girls INR 17,217, VJNT SBC TFWS INR 17,217, and SC ST INR 8,000. Direct Second Year fees include Open or OMS INR 98,000, Open EBC EWS OBC SEBC boys INR 58,181, girls INR 18,362, VJNT SBC TFWS INR 18,362, and SC ST INR 10,000.',
    status: 'Published',
  },
  {
    id: 'KB-3',
    title: 'Hostel and mess fees AY 2026-27',
    category: 'Facilities',
    source: 'Hostel and mess fee structure shared for AY 2026-27',
    tags: ['hostel fee', 'mess fee', 'mess', 'hostel deposit', 'hostel charges'],
    text: 'Hostel fee structure for AY 2026-27 includes hostel fees INR 35,000 and refundable hostel deposit INR 5,000, total INR 40,000. Mess fees per year are INR 42,000. Room availability, hostel rules, mess rules, and payment process should be confirmed by admission or hostel staff.',
    status: 'Published',
  },
  {
    id: 'KB-4',
    title: 'Programs and placement guidance',
    category: 'Programs',
    source: 'MITCORER brochure and admission material',
    text: 'MITCORER offers engineering programs including Computer Science and Engineering, Artificial Intelligence and Data Science, Civil Engineering, Electronics and Computer Engineering, Electronics and Telecommunication Engineering, and Mechanical and Rail Engineering. Placement guidance should help families compare branch-goal fit, recruiter signals, preparation path, internships, aptitude, communication, projects, and realistic career outcomes.',
    status: 'Published',
  },
  {
    id: 'KB-5',
    title: 'Engineering eligibility and branch allotment guidance',
    category: 'Eligibility',
    source: 'MITCORER First Year B.Tech Eligibility Criteria 2026-27',
    tags: ['eligibility', 'eligible', 'minimum marks', '45 percent', '40 percent', 'pcm', 'mht cet eligibility'],
    text: 'For Maharashtra State first-year B.Tech candidature, the published 2026-27 criteria require Indian citizenship, 10+2 or equivalent with Physics and Mathematics as compulsory subjects plus an accepted third subject, at least 45 percent marks taken together or 40 percent for eligible Maharashtra reserved, EWS, and PwD candidates, and appearance in all PCM MHT-CET 2026 subjects with a non-zero PCM score. All India candidature may use a non-zero positive JEE Main score or the stated PCM MHT-CET route, with preference governed by the published rules. Meeting basic eligibility permits participation; it does not guarantee CSE or another branch. Branch allotment depends on merit, category, seat type, CAP round, option-form preference, vacancies, and applicable cutoff.',
    status: 'Published',
  },
  {
    id: 'KB-6',
    title: 'MITCORER 2024-25 sanctioned intake and CAP seat matrix',
    category: 'Seat Matrix',
    tags: ['seat matrix', 'cap seats', 'sanctioned intake', 'historical seat matrix', '2024 seat matrix'],
    source: 'Maharashtra CET Cell PHSeatvacancy 2024-25, pages 1403-1407',
    text: 'Institute code 06901 seat matrix for 2024-25 lists Civil Engineering choice code 0690119110 with sanctioned intake 30 and CAP seats 30; Computer Science and Engineering choice code 0690124210 with sanctioned intake 90, CAP seats 72, Maharashtra State seats 58, All India seats 18, EWS seats 9, and TFWS choice code 0690124211T with 5 seats; Electronics and Telecommunication Engineering choice code 0690137210 with intake 60 and CAP seats 60; Mechanical Engineering choice code 0690161210 with intake 60 and CAP seats 60; Electronics and Computer Engineering choice code 0690184410 with intake 60 and CAP seats 60. This is a historical 2024-25 matrix and must not be presented as the current 2026-27 intake.',
    status: 'Published',
  },
  {
    id: 'KB-7',
    title: 'Historical CSE All India CAP Round I cutoff 2024',
    category: 'Cutoff',
    source: 'Maharashtra CET Cell 2024-25 All India CAP Round I cutoff list',
    tags: ['cse cutoff 2024', '2024 cutoff', 'historical cutoff', 'all india cutoff'],
    text: 'For choice code 0690124210, Computer Science and Engineering at institute 06901, the historical 2024 All India CAP Round I closing entry was All India merit 42429 with JEE Main score 61.2790648 for the AI seat type. This is historical reference data, not a current eligibility threshold or admission guarantee.',
    status: 'Published',
  },
  {
    id: 'KB-8',
    title: 'Historical CSE All India CAP Round I cutoff 2025',
    category: 'Cutoff',
    source: 'Maharashtra CET Cell 2025-26 All India CAP Round I cutoff list',
    tags: ['cse cutoff 2025', '2025 cutoff', 'historical cutoff', 'all india cutoff'],
    text: 'For choice code 0690124210, Computer Science and Engineering at institute 06901, the historical 2025 All India CAP Round I closing entry was All India merit 56892 with JEE score 53.9228024 for the AI seat type. This is historical reference data, not a current eligibility threshold or admission guarantee.',
    status: 'Published',
  },
  {
    id: 'KB-9',
    title: 'MITCORER current B.Tech programs and intake 2026-27',
    category: 'Programs',
    source: 'MITCORER FY B.Tech admissions page 2026-27',
    tags: ['btech programs', 'cse intake', 'cse choice code', 'first year btech', 'computer science intake'],
    sourceUrl: 'https://mitcorer.edu.in/fy-btech.php',
    text: 'The MITCORER FY B.Tech admissions page for 2026-27 lists Computer Science and Engineering with sanctioned intake 120. This is the current published intake and is different from the historical 2024-25 seat matrix, which listed CSE intake 90. Applicants must use the current academic-year CAP seat matrix and notices for choices, seats, and vacancies.',
    status: 'Published',
  },
  {
    id: 'KB-10',
    title: 'MITCORER First Year B.Tech programs, intake and choice codes',
    category: 'Programs',
    source: 'MITCORER First Year B.Tech admissions page',
    tags: ['btech programs', 'cse intake', 'cse choice code', 'first year btech', 'computer science intake'],
    sourceUrl: 'https://mitcorer.edu.in/fy-btech.php',
    text: 'For AY 2026-27, the official First Year B.Tech page lists: Artificial Intelligence and Data Science, intake 60, choice code 0690126310; Civil Engineering, 60, 0690119110; Computer Science and Engineering, 120, 0690124210; Electronics and Computer Engineering, 60, 0690184410; Electronics and Telecommunication Engineering, 60, 0690137210; and Mechanical and Rail Engineering, 60, 0690158510.',
    status: 'Published',
  },
  {
    id: 'KB-11',
    title: 'MITCORER Direct Second Year B.Tech programs and choice codes',
    category: 'Programs',
    source: 'MITCORER Direct Second Year B.Tech admissions page',
    tags: ['dse', 'direct second year', 'lateral entry', 'diploma admission', 'dse choice code'],
    sourceUrl: 'https://mitcorer.edu.in/d-sy-btech.php',
    text: 'The official Direct Second Year B.Tech page lists Civil Engineering choice code 690119110, Computer Science and Engineering 690124210, Electronics and Computer Engineering 690184410, Electronics and Telecommunication Engineering 690137210, and Mechanical and Rail Engineering 690161210. The current DSE eligibility, fees, documents, and vacancy notice must be checked for the applicable admission year.',
    status: 'Published',
  },
  {
    id: 'KB-12',
    title: 'MITCORER Polytechnic courses and intake',
    category: 'Programs',
    source: 'MITCORER Polytechnic admissions page',
    tags: ['polytechnic', 'diploma', 'polytechnic intake', 'polytechnic cse'],
    sourceUrl: 'https://mitcorer.edu.in/fy-polytechnic.php',
    text: 'The official Polytechnic page lists Civil Engineering, Computer Science and Engineering, Electronic and Telecom Engineering, and Mechanical Engineering, each with intake 60. Polytechnic eligibility, fees, required documents, and payment are listed separately from B.Tech admissions.',
    status: 'Published',
  },
  {
    id: 'KB-13',
    title: 'MITCORER category-wise admission document guidance',
    category: 'Documents',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    text: 'The MITCORER FAQ lists for Open category: SSC and HSC marksheets, MHT-CET marksheet, school leaving certificate, nationality and domicile certificate, income certificate if applicable, migration certificate if applicable, four passport photographs, nationalized-bank passbook copy, Aadhaar copy, and gap certificate if applicable. SC/ST applicants also need caste certificate and caste validity. VJ/NT/SBC/OBC/EWS applicants need the applicable category records and a valid non-creamy layer certificate where required. The exact checklist varies by route and claim.',
    status: 'Published',
  },
  {
    id: 'KB-14',
    title: 'MITCORER ACAP and institute-level admissions 2026-27',
    category: 'Admissions',
    source: 'MITCORER ACAP / Institute Level Admission page',
    tags: ['acap', 'institute level', 'management quota', 'vacancy', 'merit list', 'against cap'],
    sourceUrl: 'https://mitcorer.edu.in/acap-institute-level-admission.php',
    text: 'The official ACAP page publishes an ACAP schedule, first-year and direct-second-year provisional and final institute merit lists, vacancies after CAP-IV, ACAP notices for both routes, and Against CAP news for 2026-27. Institute-level admission must be answered from the latest listed notice, merit list, vacancy notice, and schedule; it is not a guarantee of a seat.',
    status: 'Published',
  },
  {
    id: 'KB-15',
    title: 'MITCORER facilities and hostel information',
    category: 'Facilities',
    source: 'MITCORER Admissions FAQ and infrastructure pages',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    text: 'MITCORER states that it has department laboratories, a library with digital resources and journals, campus internet facilities, classrooms, cafeteria, seminar hall, workshops, computer center, railway model room, and bus facility. The FAQ states separate boys and girls hostel facilities with RO drinking water, separate solar water-heating systems, a safe hygienic environment, and an emergency vehicle facility. Availability, room allotment, rules, routes, and timing require confirmation against current notices.',
    status: 'Published',
  },
  {
    id: 'KB-16',
    title: 'MITCORER placement support and published highlights',
    category: 'Placement',
    source: 'MITCORER website and Admissions FAQ',
    tags: ['placement companies', 'recruiters', 'highest package', 'average package', 'placement highlights'],
    sourceUrl: 'https://mitcorer.edu.in/',
    text: 'MITCORER states that its Training and Placement Cell supports placement and training, and that internships are provided as part of academic training. The website highlights list 100 plus companies visiting, 300 plus total placed, a highest package of 21 LPA, and average package of 4.4 LPA. These are website-published highlights, not a guaranteed placement outcome, package, branch-specific result, or current-year cutoff.',
    status: 'Published',
  },
  {
    id: 'KB-17',
    title: 'MITCORER official contact and travel details',
    category: 'Contact',
    source: 'MITCORER Contact page',
    tags: ['contact', 'phone', 'email', 'address', 'location', 'how to reach'],
    sourceUrl: 'https://mitcorer.edu.in/contact.php',
    text: 'Official contact: MAEER’s MIT College of Railway Engineering and Research, Industrial Estate No. 03, Barshi, Dist. Solapur, Maharashtra 413401. Email: info.mitcorer@mitpune.edu.in. Phone: +91 84599 67882 and +91 86696 62106. The Contact page lists Barshi MSRTC Bus Stand at about 5.7 km by the stated routes and Barshi Town railway station at about 4.7 km by the stated route.',
    status: 'Published',
  },
  {
    id: 'KB-18',
    title: 'MITCORER scholarship and financial-aid guidance',
    category: 'Scholarship',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    text: 'MITCORER states that government scholarships and financial-aid schemes are available for eligible students. The institution website links to MahaDBT and AICTE scholarship schemes. CampusGuard must assess a student only against the currently published scheme criteria, admission route, category, income, domicile, and required evidence; it must not promise approval or an unsupported concession amount.',
    status: 'Published',
  },
  {
    id: 'KB-19',
    title: 'MITCORER bus facility',
    category: 'Facilities',
    source: 'MITCORER Bus Facility page',
    sourceUrl: 'https://mitcorer.edu.in/bus-facility.php',
    tags: ['bus', 'transport', 'bus facility', 'bus route', 'bus stop', 'bus timing', 'bus fee'],
    text: 'MITCORER lists a bus facility under campus infrastructure. The currently published Bus Facility page does not state a route list, stops, timetable, seat availability, or transport fee. Those details must be confirmed from the current transport notice or admission staff before travel or payment.',
    status: 'Published',
  },
  {
    id: 'KB-20',
    title: 'MITCORER library and digital resources',
    category: 'Facilities',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    tags: ['library', 'digital resources', 'journals', 'book', 'borrowing', 'library timing'],
    text: 'MITCORER states that it has a well-equipped library with digital resources and journals. The public FAQ does not publish borrowing rules, timings, or access eligibility, so those operational details require confirmation from the library.',
    status: 'Published',
  },
  {
    id: 'KB-21',
    title: 'MITCORER campus internet and Wi-Fi',
    category: 'Facilities',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    tags: ['wifi', 'wi-fi', 'internet', 'campus internet', 'network'],
    text: 'MITCORER states that internet facilities are available on campus. The public FAQ does not state coverage areas, login procedure, bandwidth, or student usage policy.',
    status: 'Published',
  },
  {
    id: 'KB-22',
    title: 'MITCORER laboratories and practical facilities',
    category: 'Facilities',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    tags: ['laboratory', 'laboratories', 'lab', 'practical', 'practical facilities', 'workshop'],
    text: 'MITCORER states that well-equipped laboratories are available for all departments. The FAQ does not publish a lab-wise equipment list or access timetable.',
    status: 'Published',
  },
  {
    id: 'KB-23',
    title: 'MITCORER hostel facilities',
    category: 'Facilities',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    tags: ['hostel', 'boys hostel', 'girls hostel', 'room', 'stay', 'accommodation', 'ro water', 'solar water'],
    text: 'MITCORER states that separate boys and girls hostel facilities are available with RO drinking water, separate solar water-heating systems, a safe hygienic environment, and an emergency vehicle facility. Room availability, allotment, rules, and joining dates are not confirmed by this public FAQ and must be checked against the current hostel notice.',
    status: 'Published',
  },
  {
    id: 'KB-24',
    title: 'MITCORER placement assistance and internships',
    category: 'Placement',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    tags: ['placement assistance', 'placement cell', 'training and placement', 'internship', 'internships', 'tpo'],
    text: 'MITCORER states that a dedicated Training and Placement Cell supports placement and training, and that internship opportunities are provided as part of academic training. This does not guarantee placement, an internship, a company, or a package for an individual student.',
    status: 'Published',
  },
  {
    id: 'KB-25',
    title: 'MITCORER admission entrance examinations',
    category: 'Eligibility',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    tags: ['entrance exam', 'mht cet', 'mht-cet', 'jee main', 'jee', 'exam accepted'],
    text: 'The MITCORER FAQ states that engineering admissions are based on MHT-CET or JEE Main scores as per government norms. The detailed 2026-27 eligibility record governs candidature, qualifying subjects and marks, and route-specific conditions.',
    status: 'Published',
  },
  {
    id: 'KB-26',
    title: 'MITCORER SC and ST admission documents',
    category: 'Documents',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    tags: ['sc documents', 'st documents', 'scheduled caste', 'scheduled tribe', 'caste certificate', 'caste validity'],
    text: 'For SC/ST category, the MITCORER FAQ lists the Open-category documents plus caste certificate and caste validity certificate. The route-specific admission checklist and the current notice remain authoritative if they differ.',
    status: 'Published',
  },
  {
    id: 'KB-27',
    title: 'MITCORER OBC EWS VJNT SBC admission documents',
    category: 'Documents',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    tags: ['obc documents', 'ews documents', 'vjnt documents', 'sbc documents', 'non creamy layer', 'ncl'],
    text: 'For VJ/NT/SBC/OBC/EWS category claims, the MITCORER FAQ lists the applicable Open and category documents plus a valid non-creamy layer certificate where required. It does not state that every category uses identical proofs, so the current scheme and admission notice must be checked.',
    status: 'Published',
  },
  {
    id: 'KB-28',
    title: 'MITCORER railway engineering and career context',
    category: 'Programs',
    source: 'MITCORER Admissions FAQ',
    sourceUrl: 'https://mitcorer.edu.in/faq.php',
    tags: ['railway engineering', 'railway career', 'railway diploma', 'railways', 'metro', 'transportation'],
    text: 'MITCORER describes Railway Engineering as covering railway infrastructure, track design, signaling systems, and transportation engineering. Its FAQ lists Indian Railways, metro projects, infrastructure companies, and transportation sectors as possible career areas; these are career directions, not job guarantees.',
    status: 'Published',
  },
  {
    id: 'KB-29',
    title: 'Maharashtra CAP admission workflow',
    category: 'Admissions',
    source: 'Maharashtra CET Cell CAP admission process guidance',
    sourceUrl: 'https://cetcell.mahacet.org/',
    tags: ['cap process', 'cap round', 'allotment', 'option form', 'freeze', 'betterment', 'seat acceptance', 'reporting'],
    text: 'CAP admission proceeds through candidate registration and scrutiny, merit-list publication, option-form submission, round-wise allotment, seat acceptance or freeze/betterment decision where applicable, and institute reporting. Dates, conditions, and candidate actions must be confirmed from the current Maharashtra CET Cell notice for the relevant academic year and round.',
    status: 'Published',
  },
  {
    id: 'KB-30',
    title: 'Official Maharashtra engineering admission portals 2026-27',
    category: 'Admissions',
    source: 'Maharashtra CET Cell 2026-27 admission portals',
    sourceUrl: 'https://cetcell.mahacet.org/cap-_2026-27/',
    tags: ['deadline', 'last date', 'schedule', 'reporting date', 'btech cap portal', 'dse portal', 'polytechnic admission portal'],
    text: 'The Maharashtra CET Cell 2026-27 CAP directory links to the official First Year B.Tech and Direct Second Year Engineering portals. The Maharashtra DTE website links to the official Post-SSC Polytechnic portal. Applicants must use the current route-specific portal and its notices or important-dates section because dates change by course, academic year, and round.',
    status: 'Published',
  },
  {
    id: 'KB-31',
    title: 'Engineering attendance requirement and detained grade',
    category: 'University Rules',
    source: 'PAH Solapur University CBCS UG Engineering Rules',
    sourceUrl: 'https://www.sus.ac.in/uploads/engineering/Eng%20Revised%20Semester%20Pattern/CBCS%20UG%20Rules.pdf',
    tags: ['attendance', 'minimum attendance', '75 percent attendance', 'attendance shortage', 'detained', 'xx grade', 'condonation'],
    text: 'The university engineering CBCS rules expect regular 100% attendance in every registered theory, laboratory, seminar and project course. A maximum of 25% absence may be permitted only for valid grounds such as illness, death in the family, or another emergency beyond the student\'s control, subject to approval by the affiliated institute. A student below 75% attendance in a theory or laboratory course receives the XX grade, described as Detained.',
    status: 'Published',
  },
  {
    id: 'KB-32',
    title: 'Mandatory biometric attendance circular 2026-27',
    category: 'University Notices',
    source: 'PAH Solapur University Circular No. 06 for AY 2026-27',
    sourceUrl: 'https://www.sus.ac.in/uploads/admission/Admission%202026%2027/Circular/LMS%20Circular%20-%206%2020062026.pdf',
    tags: ['biometric attendance', 'attendance circular', 'circular 06', '2026-27 attendance'],
    text: 'PAH Solapur University Circular No. 06 for academic year 2026-27 states that biometric attendance is mandatory for students of affiliated colleges and university schools. This attendance-recording requirement does not replace the separate academic attendance threshold in the engineering rules.',
    status: 'Published',
  },
];

export const seedOfficialSources = [
  { id: 'SRC-1', title: 'MITCORER seat matrix 2024-25', documentType: 'Seat matrix', academicYear: '2024-25', sourceAuthority: 'Maharashtra CET Cell', originalFileName: '7debf34a-ca26-40f0-8df5-a7af42022ecc.pdf', status: 'Published', extractionStatus: 'Verified pages 1403-1407', linkedKnowledgeCount: 1 },
  { id: 'SRC-2', title: 'First Year B.Tech eligibility criteria 2026-27', documentType: 'Eligibility', academicYear: '2026-27', sourceAuthority: 'MITCORER official website', originalFileName: 'fy-btech-eligibility-criteria.php', status: 'Published', extractionStatus: 'Verified', linkedKnowledgeCount: 1 },
  { id: 'SRC-3', title: 'CSE All India CAP Round I cutoff 2024', documentType: 'Cutoff', academicYear: '2024-25', sourceAuthority: 'Maharashtra CET Cell', originalFileName: 'MHT_CET_Cutoff_2024_Round_I_All_India.pdf', status: 'Published', extractionStatus: 'Verified historical record', linkedKnowledgeCount: 1 },
  { id: 'SRC-4', title: 'CSE All India CAP Round I cutoff 2025', documentType: 'Cutoff', academicYear: '2025-26', sourceAuthority: 'Maharashtra CET Cell', originalFileName: 'mht-cet-cap-round-1-all-india-cutoff-2025.pdf', status: 'Published', extractionStatus: 'Verified historical record', linkedKnowledgeCount: 1 },
  { id: 'SRC-5', title: 'First Year B.Tech programs, intake and choice codes', documentType: 'Programs', academicYear: '2026-27', sourceAuthority: 'MITCORER official website', originalFileName: 'fy-btech.php', sourceUrl: 'https://mitcorer.edu.in/fy-btech.php', status: 'Published', extractionStatus: 'Verified website record', linkedKnowledgeCount: 2 },
  { id: 'SRC-6', title: 'Direct Second Year B.Tech programs and choice codes', documentType: 'Programs', academicYear: '2026-27', sourceAuthority: 'MITCORER official website', originalFileName: 'd-sy-btech.php', sourceUrl: 'https://mitcorer.edu.in/d-sy-btech.php', status: 'Published', extractionStatus: 'Verified website record', linkedKnowledgeCount: 1 },
  { id: 'SRC-7', title: 'Polytechnic programs and intake', documentType: 'Programs', academicYear: '2026-27', sourceAuthority: 'MITCORER official website', originalFileName: 'fy-polytechnic.php', sourceUrl: 'https://mitcorer.edu.in/fy-polytechnic.php', status: 'Published', extractionStatus: 'Verified website record', linkedKnowledgeCount: 1 },
  { id: 'SRC-8', title: 'Admissions FAQ, documents, facilities and scholarship guidance', documentType: 'Admissions', academicYear: '2026-27', sourceAuthority: 'MITCORER official website', originalFileName: 'faq.php', sourceUrl: 'https://mitcorer.edu.in/faq.php', status: 'Published', extractionStatus: 'Verified website record', linkedKnowledgeCount: 4 },
  { id: 'SRC-9', title: 'ACAP and institute-level admission notices', documentType: 'Admissions', academicYear: '2026-27', sourceAuthority: 'MITCORER official website', originalFileName: 'acap-institute-level-admission.php', sourceUrl: 'https://mitcorer.edu.in/acap-institute-level-admission.php', status: 'Published', extractionStatus: 'Verified website record', linkedKnowledgeCount: 1 },
  { id: 'SRC-10', title: 'CBCS UG Engineering attendance rules', documentType: 'University rules', academicYear: 'Applicable CBCS rules', sourceAuthority: 'Punyashlok Ahilyadevi Holkar Solapur University', originalFileName: 'CBCS UG Rules.pdf', sourceUrl: 'https://www.sus.ac.in/uploads/engineering/Eng%20Revised%20Semester%20Pattern/CBCS%20UG%20Rules.pdf', status: 'Published', extractionStatus: 'Verified clauses 5 and 6', linkedKnowledgeCount: 1 },
  { id: 'SRC-11', title: 'Mandatory biometric attendance Circular No. 06', documentType: 'University circular', academicYear: '2026-27', sourceAuthority: 'Punyashlok Ahilyadevi Holkar Solapur University', originalFileName: 'LMS Circular - 6 20062026.pdf', sourceUrl: 'https://www.sus.ac.in/uploads/admission/Admission%202026%2027/Circular/LMS%20Circular%20-%206%2020062026.pdf', status: 'Published', extractionStatus: 'Verified university notice', linkedKnowledgeCount: 1 },
  { id: 'SRC-12', title: 'Official contact and travel information', documentType: 'Contact', academicYear: '2026-27', sourceAuthority: 'MITCORER official website', originalFileName: 'contact.php', sourceUrl: 'https://mitcorer.edu.in/contact.php', status: 'Published', extractionStatus: 'Verified website record', linkedKnowledgeCount: 1 },
];

export function createSeedData() {
  const createdAt = nowIso();
  return {
    users: [
      { id: 'USR-APP', name: 'Applicant', email: 'applicant@example.com', role: 'applicant', passwordHash, createdAt },
      { id: 'USR-PAR', name: 'Parent', email: 'parent@example.com', role: 'parent', passwordHash, createdAt },
      { id: 'USR-STF', name: 'Shobhana Raichurkar', email: 'staff@mitcorer.edu.in', role: 'staff', passwordHash, createdAt },
      { id: 'USR-ADM', name: 'Mundhe', email: 'admin@mitcorer.edu.in', role: 'admin', passwordHash, createdAt },
    ],
    inquiries: [
      { id: 'INQ-2401', name: 'Aarav Kulkarni', role: 'Applicant', topic: 'Caste validity receipt', priority: 'High', status: 'Needs reply', city: 'Solapur', contact: 'aarav@example.com', question: 'Caste validity receipt is pending. Can I report?', createdAt, updatedAt: createdAt },
      { id: 'INQ-2402', name: 'Mrs. Deshmukh', role: 'Parent', topic: 'Hostel and fee installment', priority: 'Medium', status: 'In progress', city: 'Latur', contact: 'parent@example.com', question: 'Can hostel and mess amount be confirmed before travel?', createdAt, updatedAt: createdAt },
      { id: 'INQ-2403', name: 'Rohan Jadhav', role: 'Applicant', topic: 'TFWS and EBC documents', priority: 'New', status: 'Unassigned', city: 'Barshi', contact: 'rohan@example.com', question: 'Which documents are needed for TFWS/EBC?', createdAt, updatedAt: createdAt },
    ],
    documents: [
      { id: 'DOC-SEED-1', ownerName: 'Aarav Kulkarni', ownerEmail: 'aarav@example.com', ownerRole: 'Applicant', docName: 'CET or JEE scorecard', fileName: 'aarav-cet-scorecard.pdf', status: 'Needs correction', createdAt, updatedAt: createdAt },
      { id: 'DOC-SEED-2', ownerName: 'Rohan Jadhav', ownerEmail: 'rohan@example.com', ownerRole: 'Applicant', docName: 'CAP allotment letter', fileName: 'rohan-cap-allotment.pdf', status: 'Ready for reporting', createdAt, updatedAt: createdAt },
    ],
    content: [
      { id: 'CNT-1', title: 'Admission process 2026-27', category: 'Admissions', status: 'Published', updatedAt: createdAt },
      { id: 'CNT-2', title: 'Course intake and choice codes', category: 'Courses', status: 'Published', updatedAt: createdAt },
      { id: 'CNT-3', title: 'Hostel and transport guide', category: 'Facilities', status: 'Review', updatedAt: createdAt },
      { id: 'CNT-4', title: 'Fee records and scholarship notes', category: 'Fees', status: 'Published', updatedAt: createdAt },
    ],
    auditLogs: [
      { id: 'AUD-1', actorEmail: 'system', actorRole: 'system', action: 'seed.created', resourceType: 'system', resourceId: 'seed', details: 'Initial demo data created.', createdAt },
    ],
    refreshTokens: [],
    assistantAttachments: [],
    admissionWorkspaces: [],
    knowledge: seedKnowledge.map((item) => ({ ...item, updatedAt: createdAt })),
    officialSources: seedOfficialSources.map((item) => ({ ...item, uploadedBy: 'system', createdAt, updatedAt: createdAt })),
  };
}
